#!/bin/bash

# Usage:
# 	help       Show usage
# 	clean      Remove build files
# 	build      Build -> format -> vet
# 	test       Build -> format -> test -> vet
# 	run        Build -> format -> test -> vet -> run

tabs -2
clear
go run godo.go $@
