package err

// goErr wraps any error not explicitly generated by the code in this program.
type goErr struct {
	error
}

// Error satisfies the error interface.
func (ge goErr) Error() string {
	return ge.error.Error()
}

// Cause satisfies the error interface.
func (ge goErr) Cause() error {
	return nil
}

// LineIndex satisfies the Err interface.
func (ge goErr) LineIndex() int {
	return 0
}

// ColIndex satisfies the Err interface.
func (ge goErr) ColIndex() int {
	return 0
}

// Length satisfies the Err interface.
func (ge goErr) Length() int {
	return 0
}
